name: grabbing streams

on:
  schedule:
    - cron: '* * * * *'  # Se ejecutar치 cada minuto
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Configuraci칩n de Git
      - name: config
        run: |
          git config --global user.email "<>"
          git config --global user.name "Update"

      # Extracci칩n y actualizaci칩n de los archivos M3U8
      - name: grab m3u8 files
        run: |
          pwd
          cd ./hls/pys/
          python3 web.py https://conceptoweb-studio.com/radio/video/tvo/ ../hls/SV-23-TVO.m3u8

      # Agregar cambios al GitHub repo
      - name: git add
        run: |
          git add -A
          ls -la 

      # Commit y push de los cambios
      - name: commit & push
        run: |
          git commit -m "Canal actualizado" || echo "No hay cambios para hacer commit"
          git push
